// AUTOCOMPLETE LOCATIONS
export const SEARCH_LOCATIONS_INIT = "SEARCH_LOCATIONS_INIT";
export const SEARCH_RESET = "SEARCH_RESET";
export const SEARCH_LOCATIONS_SUCCESS = "SEARCH_LOCATIONS_SUCCESS";
export const SEARCH_LOCATIONS_FAIL = "SEARCH_LOCATIONS_FAIL";

// FORECASTS
export const GET_FORECASTS_INIT = "GET_FORECASTS_INIT";
export const GET_FORECASTS_SUCCESS = "GET_FORECASTS_SUCCESS";
export const GET_FORECASTS_FAIL = "GET_FORECASTS_FAIL";
